version: 0.1

phases:
  install:
    commands:
      - aws s3 rm s3://angularapplicationcjunior --recursive
      - aws s3 cp index.html s3://angularapplicationcjunior --acl public-read

artifacts:
  files:
    - '**/*'